import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Foundation schema for the thin slice: stations, portal users, clients, ads, action cards,
 * campaigns and their time windows, the fingerprint store, listener installs, recognition events
 * and the audit trail.
 *
 * Naming — every name is written out in full so it reads as plain English:
 *  - tables are plural nouns; timestamps end in `_at`; amounts carry their unit (`_milliseconds`);
 *  - constraints are `<table>_<subject>_<kind>`, kind being primary_key, foreign_key, unique, check
 *    or exclusion; indexes are `<table>_<columns>_index`; triggers `<table>_<what they do>`;
 *  - policies say who sees what: `<table>_station_isolation`, `<table>_admin_full_access`.
 *
 * Security (master plan, ADR-002):
 *  - every station-owned row carries station_id; composite foreign keys (id, station_id) stop a row
 *    in one station from pointing at another station's rows (foreign key checks bypass row-level
 *    security otherwise);
 *  - row-level security filters by app.current_station_id(), set per transaction by the API;
 *  - the fingerprints schema has no station data and is invisible to the API role;
 *  - tables are owned by lookup_schema_owner, which nothing logs in as;
 *  - privileges are granted per table and, where it matters, per column: password hashes, refresh
 *    tokens, approval status, platform roles and the ad → audio asset link can't be read or
 *    written by the API role directly. Those go through narrow SECURITY DEFINER functions added
 *    with the features that need them (sign-in in step 2, ingest in step 3);
 *  - no function is executable by PUBLIC unless granted, so a future SECURITY DEFINER function
 *    can't be called by a role it wasn't meant for.
 *
 * Scaling:
 *  - recognition_events (one row per identify, the fastest-growing table) is partitioned by month
 *    of received_at. Queries for a period touch only that period's partitions, and old months are
 *    detached or dropped whole rather than deleted row by row. app.create_recognition_event_partitions()
 *    creates months ahead of time; a default partition catches anything outside them. Its
 *    idempotency keys live in a small unpartitioned table so uniqueness holds across months;
 *  - fingerprints.hashes_version_1 holds every landmark hash (millions of rows per thousand ads):
 *    no per-row id, one covering index for the one lookup it serves, and a version in the name so a
 *    re-index builds a new table alongside the live one and switches over;
 *  - ids of high-volume rows are UUIDv7 generated by the API (time-ordered, so inserts stay at the
 *    end of the index); low-volume tables use gen_random_uuid();
 *  - the station context is transaction-local (set_config(..., true)), so the API works behind a
 *    transaction-mode connection pooler.
 */
export class Foundation1790960000000 implements MigrationInterface {
  name = 'Foundation1790960000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    const run = (sql: string) => queryRunner.query(sql);

    await run(`SET LOCAL search_path TO app, public`);
    await run(`CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA app`);
    await run(`CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA app`);
    // After the extensions (their operator functions must stay callable), every function the
    // schema owner creates starts with no EXECUTE for PUBLIC; each grant is explicit.
    await run(`ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC`);

    // ---- helper functions -------------------------------------------------------------------
    await run(`
      CREATE FUNCTION app.current_station_id() RETURNS uuid LANGUAGE sql STABLE PARALLEL SAFE
        AS $$ SELECT NULLIF(current_setting('app.current_station_id', true), '')::uuid $$`);
    await run(`
      CREATE FUNCTION app.current_user_id() RETURNS uuid LANGUAGE sql STABLE PARALLEL SAFE
        AS $$ SELECT NULLIF(current_setting('app.current_user_id', true), '')::uuid $$`);
    await run(`
      CREATE FUNCTION app.set_updated_at() RETURNS trigger LANGUAGE plpgsql
        AS $$ BEGIN NEW.updated_at := now(); RETURN NEW; END $$`);

    // ---- stations and people ----------------------------------------------------------------
    await run(`
      CREATE TABLE app.stations (
        id               uuid NOT NULL DEFAULT gen_random_uuid(),
        name             text NOT NULL,
        frequency_label  text NOT NULL,
        province         text,
        city             text,
        time_zone        text NOT NULL DEFAULT 'Africa/Lusaka',
        logo_object_key  text,
        status           text NOT NULL DEFAULT 'PENDING_VERIFICATION',
        is_listed_in_app boolean NOT NULL DEFAULT true,
        created_at       timestamptz NOT NULL DEFAULT now(),
        updated_at       timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT stations_primary_key PRIMARY KEY (id),
        CONSTRAINT stations_status_check CHECK (status IN
          ('PENDING_VERIFICATION', 'PENDING_REVIEW', 'ACTIVE', 'REJECTED', 'SUSPENDED'))
      )`);
    await run(`
      CREATE TABLE app.portal_users (
        id                uuid NOT NULL DEFAULT gen_random_uuid(),
        email             app.citext NOT NULL,
        password_hash     text NOT NULL,
        full_name         text NOT NULL,
        phone_number_e164 text,
        platform_role     text,
        status            text NOT NULL DEFAULT 'ACTIVE',
        created_at        timestamptz NOT NULL DEFAULT now(),
        updated_at        timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT portal_users_primary_key PRIMARY KEY (id),
        CONSTRAINT portal_users_email_unique UNIQUE (email),
        CONSTRAINT portal_users_phone_number_check CHECK (phone_number_e164 ~ '^\\+[1-9][0-9]{6,14}$'),
        CONSTRAINT portal_users_platform_role_check CHECK (platform_role IN ('SUPER_ADMIN', 'SUPPORT')),
        CONSTRAINT portal_users_status_check CHECK (status IN ('ACTIVE', 'DISABLED'))
      )`);
    await run(`
      CREATE TABLE app.station_memberships (
        station_id     uuid NOT NULL,
        portal_user_id uuid NOT NULL,
        role           text NOT NULL,
        created_at     timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT station_memberships_primary_key PRIMARY KEY (station_id, portal_user_id),
        CONSTRAINT station_memberships_station_foreign_key
          FOREIGN KEY (station_id) REFERENCES app.stations (id) ON DELETE RESTRICT,
        CONSTRAINT station_memberships_portal_user_foreign_key
          FOREIGN KEY (portal_user_id) REFERENCES app.portal_users (id) ON DELETE CASCADE,
        CONSTRAINT station_memberships_role_check CHECK (role IN ('OWNER', 'MANAGER', 'ANALYST'))
      )`);
    await run(`CREATE INDEX station_memberships_portal_user_index ON app.station_memberships (portal_user_id)`);
    await run(`
      CREATE TABLE app.refresh_tokens (
        id              uuid NOT NULL DEFAULT gen_random_uuid(),
        portal_user_id  uuid NOT NULL,
        token_family_id uuid NOT NULL,
        token_hash      bytea NOT NULL,
        expires_at      timestamptz NOT NULL,
        revoked_at      timestamptz,
        created_at      timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT refresh_tokens_primary_key PRIMARY KEY (id),
        CONSTRAINT refresh_tokens_token_hash_unique UNIQUE (token_hash),
        CONSTRAINT refresh_tokens_portal_user_foreign_key
          FOREIGN KEY (portal_user_id) REFERENCES app.portal_users (id) ON DELETE CASCADE
      )`);
    await run(`CREATE INDEX refresh_tokens_token_family_index ON app.refresh_tokens (token_family_id)`);
    await run(`CREATE INDEX refresh_tokens_portal_user_index ON app.refresh_tokens (portal_user_id)`);

    // ---- station content --------------------------------------------------------------------
    await run(`
      CREATE TABLE app.clients (
        id                     uuid NOT NULL DEFAULT gen_random_uuid(),
        station_id             uuid NOT NULL,
        name                   text NOT NULL,
        logo_object_key        text,
        default_action_card_id uuid,
        created_at             timestamptz NOT NULL DEFAULT now(),
        updated_at             timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT clients_primary_key PRIMARY KEY (id),
        CONSTRAINT clients_id_station_unique UNIQUE (id, station_id),
        CONSTRAINT clients_station_name_unique UNIQUE (station_id, name),
        CONSTRAINT clients_station_foreign_key
          FOREIGN KEY (station_id) REFERENCES app.stations (id) ON DELETE RESTRICT
      )`);
    await run(`
      CREATE TABLE app.action_cards (
        id                        uuid NOT NULL DEFAULT gen_random_uuid(),
        station_id                uuid NOT NULL,
        client_id                 uuid NOT NULL,
        schema_version            smallint NOT NULL,
        content                   jsonb NOT NULL,
        created_by_portal_user_id uuid,
        created_at                timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT action_cards_primary_key PRIMARY KEY (id),
        CONSTRAINT action_cards_id_station_unique UNIQUE (id, station_id),
        CONSTRAINT action_cards_client_foreign_key
          FOREIGN KEY (client_id, station_id) REFERENCES app.clients (id, station_id),
        CONSTRAINT action_cards_created_by_foreign_key
          FOREIGN KEY (created_by_portal_user_id) REFERENCES app.portal_users (id) ON DELETE SET NULL,
        CONSTRAINT action_cards_content_check
          CHECK (jsonb_typeof(content) = 'object' AND pg_column_size(content) < 16384)
      )`);
    await run(`
      ALTER TABLE app.clients ADD CONSTRAINT clients_default_action_card_foreign_key
        FOREIGN KEY (default_action_card_id, station_id) REFERENCES app.action_cards (id, station_id)`);

    // ---- fingerprint store (no station data; fingerprint worker only) ------------------------
    await run(`
      CREATE TABLE fingerprints.audio_assets (
        id                    uuid NOT NULL DEFAULT gen_random_uuid(),
        asset_number          integer GENERATED ALWAYS AS IDENTITY,
        content_sha256        bytea NOT NULL,
        duration_milliseconds integer NOT NULL,
        fingerprint_version   smallint NOT NULL,
        hash_count            integer NOT NULL,
        created_at            timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT audio_assets_primary_key PRIMARY KEY (id),
        CONSTRAINT audio_assets_asset_number_unique UNIQUE (asset_number),
        CONSTRAINT audio_assets_content_sha256_unique UNIQUE (content_sha256),
        CONSTRAINT audio_assets_duration_check CHECK (duration_milliseconds > 0)
      )`);
    await run(`
      CREATE TABLE fingerprints.hashes_version_1 (
        hash               bigint  NOT NULL,
        audio_asset_number integer NOT NULL,
        time_offset_frames integer NOT NULL,
        CONSTRAINT hashes_version_1_audio_asset_foreign_key
          FOREIGN KEY (audio_asset_number) REFERENCES fingerprints.audio_assets (asset_number) ON DELETE CASCADE
      )`);
    await run(`
      CREATE INDEX hashes_version_1_hash_index ON fingerprints.hashes_version_1 (hash)
        INCLUDE (audio_asset_number, time_offset_frames)`);
    await run(`CREATE INDEX hashes_version_1_audio_asset_index ON fingerprints.hashes_version_1 (audio_asset_number)`);

    // ---- ads, campaigns and their time windows ----------------------------------------------
    await run(`
      CREATE TABLE app.ads (
        id                    uuid NOT NULL DEFAULT gen_random_uuid(),
        station_id            uuid NOT NULL,
        client_id             uuid NOT NULL,
        title                 text NOT NULL,
        upload_object_key     text,
        upload_content_sha256 bytea,
        audio_asset_id        uuid,
        status                text NOT NULL DEFAULT 'AWAITING_UPLOAD',
        processing_error_code text,
        duration_milliseconds integer,
        archived_at           timestamptz,
        created_at            timestamptz NOT NULL DEFAULT now(),
        updated_at            timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT ads_primary_key PRIMARY KEY (id),
        CONSTRAINT ads_id_station_unique UNIQUE (id, station_id),
        CONSTRAINT ads_client_foreign_key FOREIGN KEY (client_id, station_id) REFERENCES app.clients (id, station_id),
        CONSTRAINT ads_audio_asset_foreign_key
          FOREIGN KEY (audio_asset_id) REFERENCES fingerprints.audio_assets (id) ON DELETE SET NULL,
        CONSTRAINT ads_status_check CHECK (status IN
          ('AWAITING_UPLOAD', 'PROCESSING', 'READY', 'NEEDS_REVIEW', 'FAILED'))
      )`);
    await run(`CREATE INDEX ads_station_updated_at_index ON app.ads (station_id, updated_at DESC)`);
    await run(`CREATE INDEX ads_audio_asset_index ON app.ads (audio_asset_id)`);
    await run(`
      CREATE TABLE app.campaigns (
        id                       uuid NOT NULL DEFAULT gen_random_uuid(),
        station_id               uuid NOT NULL,
        ad_id                    uuid NOT NULL,
        action_card_id           uuid,
        name                     text NOT NULL,
        status                   text NOT NULL DEFAULT 'DRAFT',
        active_period            tstzrange NOT NULL,
        engagement_limit         integer,
        time_window_grace_period interval NOT NULL DEFAULT '10 minutes',
        created_at               timestamptz NOT NULL DEFAULT now(),
        updated_at               timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT campaigns_primary_key PRIMARY KEY (id),
        CONSTRAINT campaigns_id_station_unique UNIQUE (id, station_id),
        CONSTRAINT campaigns_ad_foreign_key FOREIGN KEY (ad_id, station_id) REFERENCES app.ads (id, station_id),
        CONSTRAINT campaigns_action_card_foreign_key
          FOREIGN KEY (action_card_id, station_id) REFERENCES app.action_cards (id, station_id),
        CONSTRAINT campaigns_status_check CHECK (status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'ENDED')),
        CONSTRAINT campaigns_active_period_check CHECK (NOT isempty(active_period)),
        CONSTRAINT campaigns_engagement_limit_check CHECK (engagement_limit > 0),
        CONSTRAINT campaigns_one_live_campaign_per_ad_exclusion
          EXCLUDE USING gist (ad_id WITH =, active_period WITH &&) WHERE (status IN ('ACTIVE', 'PAUSED'))
      )`);
    // Days of the week are ISO numbers (1 = Monday … 7 = Sunday). Times are in the station's time
    // zone; an end before the start means the window runs past midnight.
    await run(`
      CREATE TABLE app.campaign_time_windows (
        id               uuid NOT NULL DEFAULT gen_random_uuid(),
        campaign_id      uuid NOT NULL,
        station_id       uuid NOT NULL,
        days_of_week     smallint[] NOT NULL,
        local_start_time time NOT NULL,
        local_end_time   time NOT NULL,
        CONSTRAINT campaign_time_windows_primary_key PRIMARY KEY (id),
        CONSTRAINT campaign_time_windows_campaign_foreign_key
          FOREIGN KEY (campaign_id, station_id) REFERENCES app.campaigns (id, station_id) ON DELETE CASCADE,
        CONSTRAINT campaign_time_windows_days_of_week_check
          CHECK (days_of_week <@ '{1,2,3,4,5,6,7}'::smallint[] AND cardinality(days_of_week) BETWEEN 1 AND 7),
        CONSTRAINT campaign_time_windows_not_empty_check CHECK (local_end_time <> local_start_time)
      )`);
    await run(`CREATE INDEX campaign_time_windows_campaign_index ON app.campaign_time_windows (campaign_id)`);

    // ---- listeners and recognitions ---------------------------------------------------------
    await run(`
      CREATE TABLE app.listener_installs (
        id              uuid NOT NULL DEFAULT gen_random_uuid(),
        install_id_hash bytea NOT NULL,
        platform        text NOT NULL,
        app_version     text NOT NULL,
        status          text NOT NULL DEFAULT 'ACTIVE',
        created_at      timestamptz NOT NULL DEFAULT now(),
        last_seen_at    timestamptz,
        CONSTRAINT listener_installs_primary_key PRIMARY KEY (id),
        CONSTRAINT listener_installs_install_id_hash_unique UNIQUE (install_id_hash),
        CONSTRAINT listener_installs_platform_check CHECK (platform IN ('ANDROID', 'IOS')),
        CONSTRAINT listener_installs_status_check CHECK (status IN ('ACTIVE', 'BLOCKED'))
      )`);
    await run(`
      CREATE TABLE app.recognition_events (
        id                         uuid NOT NULL,
        listener_install_id        uuid NOT NULL,
        idempotency_key            uuid NOT NULL,
        request_id                 text NOT NULL,
        captured_at                timestamptz NOT NULL,
        received_at                timestamptz NOT NULL,
        is_deferred                boolean NOT NULL DEFAULT false,
        attempt_count              smallint NOT NULL DEFAULT 1,
        completed_at               timestamptz,
        outcome                    text NOT NULL,
        fallback_reason            text,
        audio_asset_id             uuid,
        station_id                 uuid,
        campaign_id                uuid,
        action_card_id             uuid,
        hinted_station_id          uuid,
        aligned_hash_count         integer,
        match_margin               real,
        match_offset_milliseconds  integer,
        clip_duration_milliseconds integer,
        latency_milliseconds       integer,
        fingerprint_version        smallint,
        CONSTRAINT recognition_events_primary_key PRIMARY KEY (id, received_at),
        CONSTRAINT recognition_events_listener_install_foreign_key
          FOREIGN KEY (listener_install_id) REFERENCES app.listener_installs (id),
        CONSTRAINT recognition_events_audio_asset_foreign_key
          FOREIGN KEY (audio_asset_id) REFERENCES fingerprints.audio_assets (id) ON DELETE SET NULL,
        CONSTRAINT recognition_events_station_foreign_key FOREIGN KEY (station_id) REFERENCES app.stations (id),
        CONSTRAINT recognition_events_hinted_station_foreign_key
          FOREIGN KEY (hinted_station_id) REFERENCES app.stations (id),
        CONSTRAINT recognition_events_outcome_check CHECK (outcome IN
          ('PENDING', 'MATCH', 'MATCH_DEFAULT', 'CHOOSE_STATION', 'NO_MATCH', 'AMBIGUOUS',
           'INVALID_AUDIO', 'TIMEOUT', 'BUSY', 'ERROR')),
        CONSTRAINT recognition_events_captured_at_check CHECK (
          captured_at >= received_at - interval '24 hours' AND captured_at <= received_at + interval '2 minutes')
      ) PARTITION BY RANGE (received_at)`);
    await run(`
      CREATE INDEX recognition_events_station_captured_at_index ON app.recognition_events (station_id, captured_at)`);
    // Rows arrive in time order, so a block-range index finds a period cheaply at a tiny size.
    await run(`CREATE INDEX recognition_events_received_at_index ON app.recognition_events USING brin (received_at)`);
    await run(`CREATE TABLE app.recognition_events_default PARTITION OF app.recognition_events DEFAULT`);
    await run(`
      CREATE FUNCTION app.create_recognition_event_partitions(months_ahead integer) RETURNS integer
        LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog
      AS $$
      DECLARE
        first_month    timestamp := date_trunc('month', now() AT TIME ZONE 'UTC');
        month_start    timestamp;
        partition_name text;
        created_count  integer := 0;
      BEGIN
        IF months_ahead IS NULL OR months_ahead < 0 OR months_ahead > 24 THEN
          RAISE EXCEPTION 'months_ahead must be between 0 and 24';
        END IF;
        FOR month_offset IN 0..months_ahead LOOP
          month_start := first_month + make_interval(months => month_offset);
          partition_name := 'recognition_events_' || to_char(month_start, 'YYYY_MM');
          IF to_regclass('app.' || partition_name) IS NULL THEN
            EXECUTE format(
              'CREATE TABLE app.%I PARTITION OF app.recognition_events FOR VALUES FROM (%L) TO (%L)',
              partition_name,
              month_start AT TIME ZONE 'UTC',
              (month_start + interval '1 month') AT TIME ZONE 'UTC');
            created_count := created_count + 1;
          END IF;
        END LOOP;
        RETURN created_count;
      END $$`);
    await run(`SELECT app.create_recognition_event_partitions(3)`);
    // Idempotency keys for recognitions: unique per install across all months, kept only as long
    // as a phone may retry (a cleanup job removes keys older than two days).
    await run(`
      CREATE TABLE app.recognition_idempotency_keys (
        listener_install_id     uuid NOT NULL,
        idempotency_key         uuid NOT NULL,
        recognition_event_id    uuid NOT NULL,
        recognition_received_at timestamptz NOT NULL,
        created_at              timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT recognition_idempotency_keys_primary_key PRIMARY KEY (listener_install_id, idempotency_key),
        CONSTRAINT recognition_idempotency_keys_listener_install_foreign_key
          FOREIGN KEY (listener_install_id) REFERENCES app.listener_installs (id)
      )`);
    await run(`
      CREATE INDEX recognition_idempotency_keys_created_at_index ON app.recognition_idempotency_keys (created_at)`);

    await run(`
      CREATE TABLE app.audit_events (
        id                   bigint GENERATED ALWAYS AS IDENTITY,
        station_id           uuid,
        actor_portal_user_id uuid,
        action               text NOT NULL,
        entity_type          text NOT NULL,
        entity_id            uuid,
        changes              jsonb,
        request_id           text,
        occurred_at          timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT audit_events_primary_key PRIMARY KEY (id),
        CONSTRAINT audit_events_station_foreign_key FOREIGN KEY (station_id) REFERENCES app.stations (id),
        CONSTRAINT audit_events_actor_foreign_key
          FOREIGN KEY (actor_portal_user_id) REFERENCES app.portal_users (id) ON DELETE SET NULL
      )`);
    await run(`CREATE INDEX audit_events_station_occurred_at_index ON app.audit_events (station_id, occurred_at DESC)`);

    for (const table of ['stations', 'portal_users', 'clients', 'ads', 'campaigns']) {
      await run(`CREATE TRIGGER ${table}_set_updated_at BEFORE UPDATE ON app.${table}
                   FOR EACH ROW EXECUTE FUNCTION app.set_updated_at()`);
    }

    // ---- row-level security ----------------------------------------------------------------
    // A station sees itself, and a signed-in user also sees the stations they belong to
    // (needed to pick a station right after sign-in, before a station context exists).
    await run(`ALTER TABLE app.stations ENABLE ROW LEVEL SECURITY`);
    await run(`
      CREATE POLICY stations_visible_to_station_and_members ON app.stations FOR SELECT TO lookup_api
        USING (id = app.current_station_id() OR EXISTS (
          SELECT 1 FROM app.station_memberships membership
           WHERE membership.station_id = stations.id AND membership.portal_user_id = app.current_user_id()))`);
    await run(`
      CREATE POLICY stations_profile_editable_by_station ON app.stations FOR UPDATE TO lookup_api
        USING (id = app.current_station_id()) WITH CHECK (id = app.current_station_id())`);

    await run(`ALTER TABLE app.station_memberships ENABLE ROW LEVEL SECURITY`);
    await run(`
      CREATE POLICY station_memberships_visible_to_station_and_member ON app.station_memberships
        FOR SELECT TO lookup_api
        USING (station_id = app.current_station_id() OR portal_user_id = app.current_user_id())`);
    await run(`
      CREATE POLICY station_memberships_managed_by_station ON app.station_memberships FOR ALL TO lookup_api
        USING (station_id = app.current_station_id()) WITH CHECK (station_id = app.current_station_id())`);

    // Portal users: a signed-in user sees themself and the team of the station they are working
    // in, and can edit only their own row. Sign-up and sign-in go through SECURITY DEFINER
    // functions (step 2), because they run before anyone is signed in.
    await run(`ALTER TABLE app.portal_users ENABLE ROW LEVEL SECURITY`);
    await run(`
      CREATE POLICY portal_users_visible_to_self_and_team ON app.portal_users FOR SELECT TO lookup_api
        USING (id = app.current_user_id() OR EXISTS (
          SELECT 1 FROM app.station_memberships membership
           WHERE membership.portal_user_id = portal_users.id AND membership.station_id = app.current_station_id()))`);
    await run(`
      CREATE POLICY portal_users_editable_by_self ON app.portal_users FOR UPDATE TO lookup_api
        USING (id = app.current_user_id()) WITH CHECK (id = app.current_user_id())`);

    for (const table of ['clients', 'action_cards', 'ads', 'campaigns', 'campaign_time_windows', 'audit_events']) {
      await run(`ALTER TABLE app.${table} ENABLE ROW LEVEL SECURITY`);
      await run(`
        CREATE POLICY ${table}_station_isolation ON app.${table} FOR ALL TO lookup_api
          USING (station_id = app.current_station_id()) WITH CHECK (station_id = app.current_station_id())`);
    }
    await run(`ALTER TABLE app.recognition_events ENABLE ROW LEVEL SECURITY`);
    await run(`
      CREATE POLICY recognition_events_visible_to_station ON app.recognition_events FOR SELECT TO lookup_api
        USING (station_id = app.current_station_id())`);

    // No policy for anyone on these, so even a stray grant reads nothing. Only SECURITY DEFINER
    // functions touch them (sign-in in step 2, recognition in step 3).
    await run(`ALTER TABLE app.refresh_tokens ENABLE ROW LEVEL SECURITY`);
    await run(`ALTER TABLE app.recognition_idempotency_keys ENABLE ROW LEVEL SECURITY`);

    for (const table of ['stations', 'portal_users', 'station_memberships', 'clients', 'action_cards', 'ads',
                         'campaigns', 'campaign_time_windows', 'audit_events', 'recognition_events']) {
      await run(`
        CREATE POLICY ${table}_admin_full_access ON app.${table} FOR ALL TO lookup_admin_api
          USING (true) WITH CHECK (true)`);
    }

    // ---- privileges -------------------------------------------------------------------------
    // Least privilege, table by table. Nothing is granted on a whole schema, so a new table is
    // invisible to every application role until its migration grants exactly what it needs.
    await run(`GRANT USAGE ON SCHEMA app TO lookup_api, lookup_admin_api, lookup_fingerprint_worker`);
    await run(`
      GRANT EXECUTE ON FUNCTION app.current_station_id(), app.current_user_id()
        TO lookup_api, lookup_admin_api, lookup_fingerprint_worker`);

    // lookup_api — station staff working through the portal, and the listener endpoints.
    // Stations: read through the policies; edit the profile only. Approval status belongs to
    // super admins, and name or frequency changes go back through review (added with sign-up).
    await run(`GRANT SELECT ON app.stations TO lookup_api`);
    await run(`GRANT UPDATE (province, city, time_zone, logo_object_key, is_listed_in_app) ON app.stations TO lookup_api`);
    // Portal users: never the password hash (sign-in reads it through a function), and never
    // the platform role or account status (super admins only).
    await run(`
      GRANT SELECT (id, email, full_name, phone_number_e164, platform_role, status, created_at, updated_at)
        ON app.portal_users TO lookup_api`);
    await run(`GRANT UPDATE (full_name, phone_number_e164, password_hash) ON app.portal_users TO lookup_api`);
    await run(`GRANT SELECT, INSERT, DELETE ON app.station_memberships TO lookup_api`);
    await run(`GRANT UPDATE (role) ON app.station_memberships TO lookup_api`);
    await run(`GRANT SELECT, INSERT, UPDATE, DELETE ON app.clients, app.campaigns, app.campaign_time_windows TO lookup_api`);
    // Action cards are immutable versions: an edit inserts a new row.
    await run(`GRANT SELECT, INSERT ON app.action_cards TO lookup_api`);
    // Ads: the link to the shared audio asset, its duration and processing error are set only by
    // the ingest worker's function. Writing audio_asset_id directly would let a station attach
    // its own buttons to another station's audio.
    await run(`GRANT SELECT ON app.ads TO lookup_api`);
    await run(`GRANT INSERT (id, station_id, client_id, title, upload_object_key) ON app.ads TO lookup_api`);
    await run(`
      GRANT UPDATE (client_id, title, upload_object_key, upload_content_sha256, status, archived_at)
        ON app.ads TO lookup_api`);
    // Listener installs carry no station data (hashed ids only).
    await run(`GRANT SELECT, INSERT ON app.listener_installs TO lookup_api`);
    await run(`GRANT UPDATE (app_version, last_seen_at) ON app.listener_installs TO lookup_api`);
    // Recognition events are written only through SECURITY DEFINER functions (step 3); the
    // scheduler keeps future months' partitions in place.
    await run(`GRANT SELECT ON app.recognition_events TO lookup_api`);
    await run(`GRANT EXECUTE ON FUNCTION app.create_recognition_event_partitions(integer) TO lookup_api`);
    // The audit trail is append-only for every role that can log in.
    await run(`GRANT SELECT, INSERT ON app.audit_events TO lookup_api, lookup_admin_api`);

    // lookup_admin_api — super-admin endpoints. Sees everything (policies above), still not an owner.
    await run(`GRANT SELECT, INSERT, UPDATE ON app.stations TO lookup_admin_api`);
    await run(`
      GRANT SELECT (id, email, full_name, phone_number_e164, platform_role, status, created_at, updated_at)
        ON app.portal_users TO lookup_admin_api`);
    await run(`GRANT UPDATE (status) ON app.portal_users TO lookup_admin_api`);
    await run(`GRANT SELECT, INSERT, UPDATE, DELETE ON app.station_memberships TO lookup_admin_api`);
    await run(`
      GRANT SELECT ON app.clients, app.action_cards, app.ads, app.campaigns, app.campaign_time_windows,
                      app.listener_installs, app.recognition_events TO lookup_admin_api`);
    await run(`GRANT UPDATE (status) ON app.ads, app.campaigns, app.listener_installs TO lookup_admin_api`);

    // lookup_fingerprint_worker — the fingerprints schema is its alone; the API gets nothing there.
    await run(`GRANT USAGE ON SCHEMA fingerprints TO lookup_fingerprint_worker`);
    await run(`GRANT SELECT, INSERT, DELETE ON fingerprints.hashes_version_1 TO lookup_fingerprint_worker`);
    await run(`GRANT SELECT, INSERT ON fingerprints.audio_assets TO lookup_fingerprint_worker`);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    const run = (sql: string) => queryRunner.query(sql);

    // Policies that look into other tables go first, or those tables can't be dropped.
    await run(`DROP POLICY IF EXISTS stations_visible_to_station_and_members ON app.stations`);
    await run(`DROP POLICY IF EXISTS portal_users_visible_to_self_and_team ON app.portal_users`);
    for (const table of ['audit_events', 'recognition_idempotency_keys', 'recognition_events', 'listener_installs',
                         'campaign_time_windows', 'campaigns', 'ads']) {
      await run(`DROP TABLE IF EXISTS app.${table}`);
    }
    await run(`DROP FUNCTION IF EXISTS app.create_recognition_event_partitions(integer)`);
    await run(`DROP TABLE IF EXISTS fingerprints.hashes_version_1`);
    await run(`DROP TABLE IF EXISTS fingerprints.audio_assets`);
    await run(`ALTER TABLE IF EXISTS app.clients DROP CONSTRAINT IF EXISTS clients_default_action_card_foreign_key`);
    for (const table of ['action_cards', 'clients', 'refresh_tokens', 'station_memberships', 'portal_users', 'stations']) {
      await run(`DROP TABLE IF EXISTS app.${table}`);
    }
    await run(`DROP FUNCTION IF EXISTS app.set_updated_at()`);
    await run(`DROP FUNCTION IF EXISTS app.current_user_id()`);
    await run(`DROP FUNCTION IF EXISTS app.current_station_id()`);
    await run(`DROP EXTENSION IF EXISTS btree_gist`);
    await run(`DROP EXTENSION IF EXISTS citext`);
    await run(`ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON FUNCTIONS TO PUBLIC`);
  }
}
